"""updtae tables

Revision ID: 71e2e554d291
Revises: 976572b86b98
Create Date: 2023-09-14 11:56:13.780981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e2e554d291'
down_revision = '976572b86b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
