"""updtae tables

Revision ID: 976572b86b98
Revises: d9667e35ba4b
Create Date: 2023-09-14 11:12:51.282569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976572b86b98'
down_revision = 'd9667e35ba4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('create_users')
    # ### end Alembic commands ###
