"""created wishlist table

Revision ID: d9667e35ba4b
Revises: dfcf4c987b25
Create Date: 2023-09-11 22:23:31.234645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9667e35ba4b'
down_revision = 'dfcf4c987b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bicycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bicycle_id'], ['bicycles.id'], name=op.f('fk_wishlists_bicycle_id_bicycles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlists_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    # ### end Alembic commands ###
